name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: release-win
        path: D:\a\implayer\implayer\target\release\implayer.exe
