name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install libdbus-1-dev pkg-config libasound2-dev
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: target\release\implayer.exe

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: target\release\implayer.exe
